surface_planner:
  # Define the odom and world frame
  # Robot's current state and reference are expressed in the odom frame (a smooth frame that drifts with respect to the world frame).
  # The world frame is used to define the MPC tasks (e.g., footstep location), thus, it doesn't drift this frame.
  odom_frame: odom  # Use odom_frame is this param is empty
  world_frame: point_cloud_odom  # Use odom_frame is this param is empty

  # Define the topic name for subscrition and publication of the MPC node
  # Note that the robot state and MPC references needs to be expressed in the odom frame.
  # Instead, for efficiency reasons, the MPC plan is expressed in the world frame.
  robot_state_topic: /motion_control_manager/whole_body_state

  # Define the robot description: URDF, feet, nominal posture, locked joints, and armature
  joints_to_be_locked: [actuated_lidar_dynamixel]
  robot_description: anymal_description
  3d_feet: [LF_FOOT, LH_FOOT, RF_FOOT, RH_FOOT]

  # Use URDF of the environment or plane_seg visualisation.
  plane_seg: true
  # Extract the scene as a single .stl file to post-process with hpp-affordance --> extract_methodId=0
  # Extract the scene as a multiple .stl files --> extract_methodId=1
  extract_methodId: 1

  # PlaneSeg parameters for postprocessing
  margin_inner: 0.02  # Margin in [m] inside the convex surfaces (sfae footstep planinng)
  margin_outer: 0.02  # Margin in [m] ouside the convex surfaces (collision avoidance)
  n_points: 10  # Maximum Number of points for for each convex surface

  # Method to remove the overlapping between surfaces :
  # 1. Run the list of surfaces starting with the lowest.
  # 2. Decomposes the lowest surface in set of convex ones by removing the upper surfaces that overlap it. (Tesselation algorithm).
  # 3. Delate some of the remaining surfaces from the list and continue using one of the following method.
  #     - BASIC (0): Intersect the lowest polygon with all the upper polygon that overlay and keep all remaining surfaces.
  #     - AREA (1): After difference and decomposition with the upper polygons, select only the remining polygon
  #             whose area is superior to min_area arg.
  #     - CONVEX (2): Apply the difference with the convex hull of the upper surfaces that intersect, to avoid
  #               having small surfaces between the upper surfaces.
  #     - AREA_CONVEX (3): Both 1 and 2 methods.
  method_id: 3
  poly_size: 10  # Maximum size of the polygon for the convex decomposition.
  min_area: 0.03  # Area under which the remaining surfaces is delated.

  # Surface planner parameters independant from MPC-Walkgen
  N_phase: 2  # Number of phases computing by SL1M (1 phase = whole walking gait, 4 foot moving)
  com: false  # Optimize CoM trajectory in SL1M
  fitsize_x: 10  # Number of point on x-axis (base frame) to evaluate the terrain height
  fitsize_y: 5  # Number of point on y-axis (base frame) to evaluate the terrain height
  fitlength: 0.3  # Square size [m] around the position of the robot to evaluate the terrain height
  recompute_slope: true  # Recompute the slope of the terrain for each contact phase configuration

  # MPC-Walkgen parameters
  N_phase_return: walkgen/N_phase_return  # Number of phases returned by SL1M
  typeGait: walkgen/typeGait  # "Walk" or "Trot"
  dt: walkgen/dt
  N_ss: walkgen/N_ss
  N_ds: walkgen/N_ds
  N_uss: walkgen/N_uss
  N_uds: walkgen/N_uds

  # Heightmap and URDF path
  path: /usr/local/share/uoe_lab_resources
  # Stairs up
  # stl: /meshes/lab_scene.stl
  # Stairs down
  stl: /meshes/lab_scene_2.stl

  # Topic to exchange with footstep planner
  footstep_manager_topic: /walkgen/fstep_manager
  surface_planner_topic: /walkgen/surface_planner
  plane_seg_topic: /plane_seg/hull_marker_array

  # Visualization, publish marker and markerArray for RVIZ visualization
  visualization: true
